docs: 📄 added page for dataset collections
fairdataihub/SODA-for-SPARC-Docs pull request #121
Opened 2022-08-02 17:10 UTC by slugb0t

Collections page added to documentation page in manage datasets section.

2022-08-02 17:45 UTC, megasanjay approved these changes

2022-08-02 18:03 UTC, aaronm-2112 requested changes
For the How To section can you change step two so that it says Add / delete collection names.
It is a little confusing as is. 

To go an extra step maybe it is best to make a h3 for describing how to add collection names and a separate h3 for describing how to delete them.

2022-08-03 19:13 UTC, slugb0t commented
> For the How To section can you change step two so that it says Add / delete collection names. It is a little confusing as is.
> 
> To go an extra step maybe it is best to make a h3 for describing how to add collection names and a separate h3 for describing how to delete them.

Updated based on feedback and also added details about dataset collections can only be modified by owner or manager.

2022-08-05 17:35 UTC, aaronm-2112 approved these changes
Looks good. We can merge this after the 8.0.0 release.

2022-09-15 17:21 UTC, merged